### ISSUE TITLE
Can't bind to 'data' since it isn't a known property of 'ng-data-picker'.

### ISSUE THREAD

**Issue by jitan16** [hiyali/ng-data-picker#2]
Hi, 

I'm getting this error, Do I need to update my angular version? Current version is Angular 5.

See the screenshot below. Thank you.

http://prntscr.com/owcjrn

**Comment by hiyali** [comment]
@jitan16 Thanks for your feedback.

But I must say that this component not for version 5+ of Angular  (not test on it at least), **I haven’t updated it for two years**.
