### ISSUE TITLE
Adding count in currentIndex

### ISSUE THREAD

**Issue by devjitan** [hiyali/ng-data-picker#4]
Hi, how can I change the currentIndex when using click event. See the screenshot below

![image](https://user-images.githubusercontent.com/45889861/73417585-8d49ec00-4353-11ea-911f-2011889958e7.png)

Thanks,

Jim

**Comment by hiyali** [comment]
@devjitan change the `currentIndex` of the `data`, and set the `data` to the picker.
See the `README.md` for more information.

**Comment by devjitan** [comment]
@hiyali thank you for your response. Unfortunately I didn't work. 

The **currentIndex** of the **data** is changed but still doesn't change on the wheel

![image](https://user-images.githubusercontent.com/45889861/73423597-92b13180-4367-11ea-883e-cc819192e887.png)

**Comment by hiyali** [comment]
It's a common issue, the binding logic of Angular was not detected the data already changed, so the UI layer didn't render the changes.
So, you must set data to the picker, not just change the property. And the Angular should detect the data has changed.

Some code like (NOT EQUAL) below:
```javascript
data[i].currentIndex = 4
this.picker.data = data
```

**Comment by devjitan** [comment]
Here's my sample code @hiyali 

```
degrees = [{
  currentIndex : 0,
  list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
}]

updateDegrees() {
  let copy = {...this.degrees[0]};
  copy.currentIndex = copy.currentIndex + 1;
  this.degrees[0] = copy;
}
```

**Comment by devjitan** [comment]
```
degrees = [
    {
      currentIndex : 0,
      list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
    }
  ]

  updateDegrees() {
      this.degrees[0] = {...this.degrees[0], currentIndex:  this.degrees[0].currentIndex + 1};
  }
```

**Comment by devjitan** [comment]
I tried also the static value and still not working. 

```
degrees = [
  {
    currentIndex: 0,
    list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
  }
];

updateDegrees() {
    this.degrees[0] = {
      currentIndex: 1,
      list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
    }
}
```

**Comment by hiyali** [comment]
try this:
```typescript
updateDegrees() {
    this.degrees = [{
        currentIndex: 1,
        list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
    }]
    // this.degrees = newDegrees, NOT this.degrees[n] = something
}
```

**Comment by hiyali** [comment]
try this:
```typescript
updateDegrees() {
    pickerInstance.setGroupData(0, {
        currentIndex: 1,
        list: ['0°', '1°', '2°', '3°', '4°', '5°', '6°', '7°', '8°', '9°', '10°']
    })
}
```

**Comment by hiyali** [comment]
Please see the demos. Thank you.
