### ISSUE TITLE
Angular 11 compatibility 

### ISSUE THREAD

**Issue by shaya-tabit** [hiyali/ng-data-picker#7]
Hey, I'm unable to run it on an Angular 11 app, getting error:
`Value at position 10 in the NgModule.declarations of MyAppModule is not a reference. Value could not be determined statically.(-991010)`
Is there something I'm doing wrong? 
Thx

![2021-07-27 15_45_42-Window](https://user-images.githubusercontent.com/72202898/127156229-3902ca08-155d-4a43-b509-ceed6fcf23c4.png)

**Comment by hiyali** [comment]
Hey @shaya-tabit  , as you can see in the description of the project this repository is only compatible with angular 4.x versions, not maintained this project for a long time, PRs are welcome to ingratiate to the new versions of angular, but I have no time to do these works for now

in other words, you need to pick other libs
